<?php

namespace App\Helpers;

class ProductData
{
    public static function getProductsByCategory($categoryCode)
    {
        $products = [
            'CAT-CPU' => [
                'Intel Core i9-14900K',
                'Intel Core i7-14700K',
                'Intel Core i5-14600K',
                'AMD Ryzen 9 7950X',
                'AMD Ryzen 7 7800X3D',
                'AMD Ryzen 5 7600X',
                'Intel Core i3-14100F',
                'AMD Ryzen 9 7900X',
                'Intel Core i9-13900K',
                'AMD Ryzen Threadripper 7970X',
            ],
            'CAT-GPU' => [
                'NVIDIA GeForce RTX 4090',
                'NVIDIA GeForce RTX 4080 Super',
                'NVIDIA GeForce RTX 4070 Ti',
                'AMD Radeon RX 7900 XTX',
                'AMD Radeon RX 7800 XT',
                'NVIDIA GeForce RTX 4060',
                'AMD Radeon RX 7600',
                'Intel Arc A770',
                'NVIDIA GeForce RTX 4070 Super',
                'AMD Radeon RX 7700 XT',
            ],
            'CAT-RAM' => [
                'Corsair Vengeance DDR5 32GB',
                'G.Skill Trident Z5 RGB 32GB',
                'Kingston Fury Beast DDR5 16GB',
                'Crucial Pro DDR5 32GB',
                'TeamGroup T-Force Delta 32GB',
                'Corsair Dominator Platinum 64GB',
                'G.Skill Ripjaws S5 32GB',
                'Kingston Fury Renegade 32GB',
                'ADATA XPG Lancer 16GB',
                'Patriot Viper Venom 32GB',
            ],
            'CAT-SSD' => [
                'Samsung 990 PRO 2TB NVMe',
                'WD Black SN850X 2TB NVMe',
                'Crucial T700 2TB PCIe 5.0',
                'Kingston KC3000 1TB NVMe',
                'Samsung 870 EVO 2TB SATA',
                'Seagate FireCuda 530 1TB',
                'ADATA XPG Gammix S70 2TB',
                'Crucial MX500 1TB SATA',
                'SK Hynix Platinum P41 2TB',
                'TeamGroup Cardea A440 1TB',
            ],
            'CAT-MTB' => [
                'ASUS ROG Maximus Z790 Hero',
                'MSI MPG Z790 Carbon WiFi',
                'Gigabyte Z790 AORUS Master',
                'ASRock Z790 Taichi',
                'ASUS TUF Gaming B650-PLUS',
                'MSI MAG B760 Tomahawk',
                'Gigabyte B650 AORUS Elite',
                'ASUS ROG Strix X670E-E',
                'MSI MEG X670E Godlike',
                'ASRock B650M Pro RS',
            ],
            'CAT-PSU' => [
                'Corsair RM850x 850W',
                'EVGA SuperNOVA 1000 G7',
                'Seasonic Focus GX-750',
                'be quiet! Dark Power 13 850W',
                'Cooler Master V850 SFX',
                'Corsair HX1200 1200W',
                'Thermaltake Toughpower GF3 1000W',
                'NZXT C1000 Gold',
                'ASUS ROG Thor 1200P2',
                'SilverStone SX1000 Platinum',
            ],
            'CAT-CASE' => [
                'NZXT H7 Flow',
                'Corsair 5000D Airflow',
                'Lian Li PC-O11 Dynamic',
                'Fractal Design Meshify 2',
                'Cooler Master HAF 700',
                'Phanteks Eclipse P500A',
                'be quiet! Silent Base 802',
                'Thermaltake Core P6',
                'Lian Li LANCOOL III',
                'Fractal Design North',
            ],
            'CAT-MNT' => [
                'ASUS ROG Swift PG27AQDM',
                'Samsung Odyssey G7 27"',
                'LG UltraGear 27GP950-B',
                'Dell Alienware AW3423DWF',
                'Gigabyte M28U 28"',
                'MSI Optix MAG274QRF-QD',
                'ViewSonic Elite XG270QG',
                'BenQ EX2710Q 27"',
                'Acer Predator X34',
                'HP OMEN 27k 27"',
            ],
            'CAT-CLG' => [
                'NZXT Kraken Z73 RGB',
                'Corsair iCUE H150i Elite',
                'Noctua NH-D15 Chromax',
                'Cooler Master Hyper 212',
                'be quiet! Dark Rock Pro 4',
                'Arctic Liquid Freezer II 360',
                'Deepcool LS720',
                'Lian Li Galahad 360',
                'Thermaltake TOUGHAIR 510',
                'EK-AIO Nucleus CR360',
            ],
            'CAT-KBD' => [
                'Razer Huntsman V3 Pro',
                'Corsair K100 RGB Optical',
                'Logitech G915 TKL Wireless',
                'SteelSeries Apex Pro',
                'Ducky One 3 Mini',
                'Keychron Q1 Pro',
                'ASUS ROG Azoth',
                'Wooting 60HE',
                'HyperX Alloy Origins 65',
                'Razer BlackWidow V4',
            ],
            'CAT-MSE' => [
                'Logitech G502 X Plus',
                'Razer DeathAdder V3 Pro',
                'Logitech G Pro X Superlight',
                'SteelSeries Aerox 5',
                'Glorious Model O 2',
                'Razer Viper V2 Pro',
                'Corsair Dark Core RGB Pro',
                'Pulsar X2 Wireless',
                'Zowie EC2-CW',
                'Razer Basilisk V3',
            ],
        ];

        return $products[$categoryCode] ?? [];
    }
}
